### ISSUE TITLE
Installtion process not working (CLI or manual)

### ISSUE THREAD

**Issue by ahmedsomaa** [TheDuckUI/ui#3]
## Description

I tried to follow the CLI installation steps in the introduction page and the button ones, but they didn't work. It worked through manual but there are other required dependencies that has to be installed like `@radix-ui/react-tooltip`, `DuckCommand` ...etc which you either need to install or have them copy paste from the component file itself which is not yet available.

## Screenshots
Here the package is installed but the module is not read and you cannot import as well.

![image](https://github.com/user-attachments/assets/6578f3e2-2b93-405f-b47f-2165058778b3)

**Comment by wildduck2** [comment]
hey there

the CLI is old and  we are running new version you can use the manual components form the documentation like this 


![image](https://github.com/user-attachments/assets/cb2edaae-a969-44fb-bbb4-be6599bf9809)

thanks for your pull and enjoy duck using manual components until we ship the the final NPM version of it 
we are running multi program in parallel so we and still refactoring the base of this lib until we get a stable v that will scale well  with us

**Comment by wildduck2** [comment]
and the documentation is not finished there's missing parts of the components manual installation even so stay toned today a new version will be uploaded
